oAuth:
  clientId:
  clientSecret:
serviceType: <service type name here>
bandPosition: <target band position if sendAll is disabled>
teamNames:
 - team 1
 - team 2
sendAll: false
backupNumber: "(###) ###-####"
failureLogEmails:
 - email@domain.com
 - email2@domain.com
message: The dot is up.
messageType: iMessage
debug: true
