name: dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.4

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  path: ^1.9.0
  http: ^1.5.0
  yaml: ^3.1.3
  oauth2: ^2.0.5
  logging: ^1.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
